// <auto-generated />
using KutuphanMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KutuphanMVC.Migrations
{
    [DbContext(typeof(KutuphanContext))]
    partial class KutuphanContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("KutuphanMVC.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ADminAd")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminSifre")
                        .HasColumnType("TEXT");

                    b.HasKey("AdminId");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("KutuphanMVC.Models.EmanetKitap", b =>
                {
                    b.Property<int>("EmanetKitapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KitapId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmanetKitapId");

                    b.ToTable("emanetKitaps");
                });

            modelBuilder.Entity("KutuphanMVC.Models.Kitap", b =>
                {
                    b.Property<int>("KitapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KitapAd")
                        .HasColumnType("TEXT");

                    b.Property<string>("KitapSayfaSayisi")
                        .HasColumnType("TEXT");

                    b.Property<string>("KitapTuru")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kresimad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Yayinevi")
                        .HasColumnType("TEXT");

                    b.Property<string>("YazarAd")
                        .HasColumnType("TEXT");

                    b.HasKey("KitapId");

                    b.ToTable("kitaps");
                });

            modelBuilder.Entity("KutuphanMVC.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KullaniciAd")
                        .HasColumnType("TEXT");

                    b.Property<string>("KullaniciEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("KullaniciSifre")
                        .HasColumnType("TEXT");

                    b.Property<string>("KullaniciTel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resimadi")
                        .HasColumnType("TEXT");

                    b.HasKey("KullaniciId");

                    b.ToTable("kullanicis");
                });

            modelBuilder.Entity("KutuphanMVC.Models.Mesaj", b =>
                {
                    b.Property<int>("MesajId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MesajGonderen")
                        .HasColumnType("TEXT");

                    b.Property<string>("MesajKonu")
                        .HasColumnType("TEXT");

                    b.Property<string>("MesajMesaj")
                        .HasColumnType("TEXT");

                    b.HasKey("MesajId");

                    b.ToTable("mesajs");
                });
#pragma warning restore 612, 618
        }
    }
}
